/* ═══════════════════════════════════════════════
   AARAINA — Product Catalogue
   Single source of truth. Import on every page
   that needs product data.
   ═══════════════════════════════════════════════ */

const PRODUCTS = [
  {
    id: "navy-zari-silk",
    name: "Navy Zari Silk Saree",
    region: "Tamil Nadu",
    weave: "Kanjivaram",
    price: 13500,
    image: "navy-zari-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Gold zari motifs · Deep navy · Festive",
    tags: ["silk", "festive", "bridal"],
    colors: ["#1a2a6c"],
    featured: true,
  },
  {
    id: "teal-zari-silk",
    name: "Teal Zari Silk Saree",
    region: "Tamil Nadu",
    weave: "Kanjivaram",
    price: 13500,
    image: "teal-zari-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Gold zari motifs · Peacock teal · Festive",
    tags: ["silk", "festive", "bridal"],
    colors: ["#008080"],
    featured: true,
  },
  {
    id: "crimson-zari-silk",
    name: "Crimson Zari Silk Saree",
    region: "Tamil Nadu",
    weave: "Kanjivaram",
    price: 14000,
    image: "crimson-zari-silk.jpeg",
    imgPos: "right",
    badge: "Bridal",
    badgeClass: "new",
    desc: "Gold zari border · Deep red · Bridal",
    tags: ["silk", "festive", "bridal"],
    colors: ["#8b0000"],
    featured: true,
  },
  {
    id: "forest-zari-silk",
    name: "Forest Green Silk Saree",
    region: "Tamil Nadu",
    weave: "Kanjivaram",
    price: 13500,
    image: "forest-green-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Gold zari motifs · Bottle green · Festive",
    tags: ["silk", "festive"],
    colors: ["#1b4332"],
    featured: false,
  },
  {
    id: "orange-silver-silk",
    name: "Orange Silver Zari Saree",
    region: "Madhya Pradesh",
    weave: "Chanderi",
    price: 8900,
    image: "orange-silver-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Silver zari · Burnt orange · Everyday elegance",
    tags: ["silk", "daily", "festive"],
    colors: ["#cc5500"],
    featured: false,
  },
  {
    id: "mustard-silver-silk",
    name: "Mustard Silver Silk Saree",
    region: "Madhya Pradesh",
    weave: "Chanderi",
    price: 8500,
    image: "mustard-silver-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Silver zari motifs · Golden yellow · Casual chic",
    tags: ["silk", "daily"],
    colors: ["#e3a020"],
    featured: false,
  },
  {
    id: "slate-gold-silk",
    name: "Slate Gold Silk Saree",
    region: "Tamil Nadu",
    weave: "Kanjivaram",
    price: 12800,
    image: "slate-gold-silk.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Gold zari · Gunmetal grey · Heritage motifs",
    tags: ["silk", "festive", "bridal"],
    colors: ["#708090"],
    featured: false,
  },
  {
    id: "red-black-cotton",
    name: "Red & Black Zari Cotton",
    region: "West Bengal",
    weave: "Tant",
    price: 5200,
    image: "red-black-cotton.jpeg",
    imgPos: "center",
    badge: "Ready Collection",
    badgeClass: "",
    desc: "Contrast border · Copper zari · Casual festive",
    tags: ["cotton", "daily", "festive"],
    colors: ["#c0392b", "#1a1a1a"],
    featured: false,
  },
  {
    id: "pink-navy-cotton",
    name: "Pink & Navy Zari Cotton",
    region: "West Bengal",
    weave: "Tant",
    price: 4800,
    image: "pink-navy-cotton.jpeg",
    imgPos: "center",
    badge: "Ready Collection",
    badgeClass: "",
    desc: "Contrast border · Copper zari · Vibrant",
    tags: ["cotton", "daily", "festive"],
    colors: ["#e91e8c", "#0d1b6e"],
    featured: false,
  },
  {
    id: "navy-silver-linen",
    name: "Navy Silver Linen Saree",
    region: "Bihar",
    weave: "Bhagalpuri",
    price: 6200,
    image: "navy-silver-linen.jpeg",
    imgPos: "left",
    badge: "Handloom",
    badgeClass: "",
    desc: "Silver zari · Navy linen · Everyday luxury",
    tags: ["silk", "daily"],
    colors: ["#1a237e"],
    featured: false,
  },
  {
    id: "purple-mustard-cotton",
    name: "Purple & Mustard Silk Cotton",
    region: "Tamil Nadu",
    weave: "Chettinad",
    price: 5900,
    image: "purple-mustard-cotton.jpeg",
    imgPos: "center",
    badge: "Handloom",
    badgeClass: "",
    desc: "Contrast border · Copper motifs · Festive",
    tags: ["cotton", "festive"],
    colors: ["#6a0572", "#e3a020"],
    featured: false,
  },
];

/* ── Helpers ── */

/** Find a single product by id */
function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

/** Return the first `n` featured products */
function getFeaturedProducts(n = 3) {
  return PRODUCTS.filter((p) => p.featured).slice(0, n);
}
